name = "HTTP"
grammar = "http"
path_suffixes = ["http", "rest"]
line_comment = "# "
autoclose_before = ";:.,=}])>"
word_characters = ["-"]
completion_query_characters = ["-", ":", "/", "{", " "]
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
]
