#!/bin/bash

# REST Client Extension - GIF Recording Script
# This script helps you record a demonstration GIF for the extension

echo "🎬 REST Client Extension - Recording Guide"
echo "==========================================="
echo ""
echo "To create a GIF demonstration, follow these steps:"
echo ""
echo "1. PREPARE YOUR SCREEN"
echo "   - Close unnecessary windows"
echo "   - Set Zed to a readable font size (14-16pt)"
echo "   - Resize Zed window to 1280x720 or 1920x1080"
echo "   - Have a clean .http file ready"
echo ""
echo "2. RECORDING TOOLS"
echo ""
echo "   macOS:"
echo "   - QuickTime Player: File → New Screen Recording"
echo "   - Or use: https://getkap.co/ (free, great for GIFs)"
echo ""
echo "   Cross-platform:"
echo "   - OBS Studio: https://obsproject.com/ (free)"
echo "   - LICEcap: https://www.cockos.com/licecap/ (free GIF recorder)"
echo ""
echo "3. RECORDING SCRIPT"
echo ""
echo "   Scene 1: Setup Keymap (5 seconds)"
echo "   - Press Cmd+,"
echo "   - Click 'Open Keymap'"
echo "   - Show the JSON shortcut"
echo "   - Press Cmd+S"
echo ""
echo "   Scene 2: Create File (3 seconds)"
echo "   - File → New"
echo "   - Type 'test.http' in filename"
echo "   - Save"
echo ""
echo "   Scene 3: Write Request (5 seconds)"
echo "   - Type slowly and clearly:"
echo "     ### Get user info"
echo "     GET https://jsonplaceholder.typicode.com/users/1"
echo ""
echo "   Scene 4: Execute Request (5 seconds)"
echo "   - Click anywhere in the request"
echo "   - Press Ctrl+Enter"
echo "   - Show terminal with response"
echo "   - Wait 2 seconds on the response"
echo ""
echo "   Scene 5: Multiple Requests (8 seconds)"
echo "   - Add another request:"
echo "     ### Get all users"
echo "     GET https://jsonplaceholder.typicode.com/users"
echo "   - Click in the second request"
echo "   - Press Ctrl+Enter"
echo "   - Show response"
echo ""
echo "   Total: ~26 seconds"
echo ""
echo "4. CONVERT VIDEO TO GIF"
echo ""
echo "   Using ffmpeg (install via: brew install ffmpeg):"
echo "   $ ffmpeg -i recording.mov -vf \"fps=10,scale=800:-1:flags=lanczos\" -c:v gif output.gif"
echo ""
echo "   Or use online converter:"
echo "   - https://ezgif.com/video-to-gif"
echo "   - https://cloudconvert.com/mp4-to-gif"
echo ""
echo "5. OPTIMIZE GIF SIZE"
echo ""
echo "   Using gifsicle (install via: brew install gifsicle):"
echo "   $ gifsicle -O3 --lossy=80 output.gif -o optimized.gif"
echo ""
echo "   Or use online optimizer:"
echo "   - https://ezgif.com/optimize"
echo ""
echo "6. RECOMMENDED GIF SETTINGS"
echo "   - Resolution: 800x600 or 1000x750"
echo "   - FPS: 10-15 (smooth but small file)"
echo "   - Duration: 20-30 seconds max"
echo "   - File size: Under 5MB (GitHub limit: 10MB)"
echo ""
echo "7. WHERE TO ADD THE GIF"
echo "   - README.md (top section after title)"
echo "   - Create assets/ folder: assets/demo.gif"
echo "   - Reference in markdown:"
echo "     ![Demo](assets/demo.gif)"
echo ""
echo "==========================================="
echo ""
echo "💡 Quick Command for macOS Recording:"
echo ""
echo "# Start recording with QuickTime"
echo "open -a 'QuickTime Player' --new"
echo ""
echo "# After recording, convert to GIF:"
echo "ffmpeg -i ~/Desktop/Screen\\ Recording.mov -vf \"fps=10,scale=800:-1:flags=lanczos\" -loop 0 demo.gif"
echo ""
echo "# Optimize:"
echo "gifsicle -O3 --lossy=80 demo.gif -o assets/demo.gif"
echo ""
echo "==========================================="
echo ""
echo "🎯 ALTERNATIVE: Create an Asciinema Recording"
echo ""
echo "For terminal-based demo:"
echo "1. Install: brew install asciinema"
echo "2. Record: asciinema rec demo.cast"
echo "3. Upload: asciinema upload demo.cast"
echo "4. Get shareable link!"
echo ""
echo "==========================================="
echo "Ready to record? Press any key to open recording checklist..."
read -n 1 -s

echo ""
echo "📋 RECORDING CHECKLIST"
echo ""
echo "□ Font size increased (14-16pt)"
echo "□ Window size set (1280x720)"
echo "□ .http file prepared"
echo "□ Terminal visible"
echo "□ No distractions on screen"
echo "□ Recording tool ready"
echo "□ Test.http file content ready:"
echo ""
cat << 'HTTPFILE'
### Get user info
GET https://jsonplaceholder.typicode.com/users/1

### Get all users
GET https://jsonplaceholder.typicode.com/users
HTTPFILE
echo ""
echo "✅ Ready to record!"
